# Generated by Django 3.0.8 on 2020-08-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0002_auto_20200816_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ground',
            name='ground_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ground',
            name='image',
            field=models.FileField(upload_to='ground/'),
        ),
    ]
