# Generated by Django 3.0.8 on 2020-07-30 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('ground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ground.Ground')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
