# Generated by Django 3.0.8 on 2020-08-21 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_auto_20200813_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('cafe_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to='cafe/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'cafe',
            },
        ),
    ]
