# Generated by Django 3.0.8 on 2020-08-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='image',
            field=models.FileField(upload_to='images/cafe/'),
        ),
    ]
